version: '3.9'
services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: maria777
      MARIADB_DATABASE: guacamole
      MARIADB_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - guacamole-network

  rest-with-spring-boot-guacamole:
    image: pacbittencourt/guacamole
    restart: always
    build: ./upgraded-guacamole
    working_dir: /upgraded-guacamole
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mariadb://db:3308/guacamole?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: maria777
    ports:
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - guacamole-network

networks:
  guacamole-network:
    driver: bridge