cors:
  originPatterns: https://localhost:3000,https://localhost:8080,https://erudio.com.br
file:
  upload-dir: /Users/pedro.bittencourt/Projects/upgraded-guacamole/files-upload
security:
  jwt:
    token:
      secret-key: pedroca
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/guacamole?useTimezone=true&serverTimezone=UTC
    username: root
    password: maria777
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
spring-doc:
  paths-to-match:
    - /api/**/v1/**
    - /auth/**
  swagger-ui:
    use-root-path: true
