cors:
  originPatterns: https://localhost:3000,https://localhost:8080,https://erudio.com.br
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/guacamole?useTimezone=true&serverTimezone=UTC
    username: root
    password: maria777
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
spring-doc:
  paths-to-match:
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true
