spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guacamole?useTimezone=true&serverTimezone=UTC
    username: root
    password: maria777
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
spring-doc:
  paths-to-match:
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true
